package evacuatzia_proj.sqlhelpers.beans;

// Generated Aug 24, 2014 8:25:09 PM by Hibernate Tools 4.0.0

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserRolesId generated by hbm2java
 */
@Embeddable
public class UserRolesId implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 2607611617339666199L;
	private String userName;
	private String roleName;

	public UserRolesId() {
	}

	public UserRolesId(String userName, String roleName) {
		this.userName = userName;
		this.roleName = roleName;
	}

	@Column(name = "userName", nullable = false, length = LoginAccounts.USERNAME_TEXT_LENGTH)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "roleName", nullable = false, length = UserRoles.ROLE_TEXT_LENGTH)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserRolesId))
			return false;
		UserRolesId castOther = (UserRolesId) other;

		return ((this.getUserName() == castOther.getUserName()) || (this.getUserName() != null
				&& castOther.getUserName() != null && this.getUserName().equals(castOther.getUserName())))
				&& ((this.getRoleName() == castOther.getRoleName()) || (this.getRoleName() != null
						&& castOther.getRoleName() != null && this.getRoleName().equals(castOther.getRoleName())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result + (getRoleName() == null ? 0 : this.getRoleName().hashCode());
		return result;
	}


	// For debuging
	@Override
	public String toString() {
		return "username: " + userName + ", role:" + roleName;
	}
	
}
